### ISSUE TITLE
VRAM問題+PLUG臃腫問題+USB訂製問題

### ISSUE THREAD

**Issue by IlikemacOS** [Xmingbai/asrock-Z490M-itx-ac-hackintosh-Opencore#1]
hello，VRAM不應該是1536MB嗎，您這裡怎麼是2048MB
PLUG的體積稍微過大
USB-C機殼插口無法使用，USB-C後置插口無法正常使用擴展塢
望解決

**Comment by CodingOX** [comment]
> hello，VRAM不應該是1536MB嗎，您這裡怎麼是2048MB
> PLUG的體積稍微過大
> USB-C機殼插口無法使用，USB-C後置插口無法正常使用擴展塢
> 望解決

why close the issue... fixed?
