### ISSUE TITLE
GPU 温度无法获取，风扇转速也无法获取

### ISSUE THREAD

**Issue by CodingOX** [Xmingbai/asrock-Z490M-itx-ac-hackintosh-Opencore#2]
如图所示：
![image](https://user-images.githubusercontent.com/9800933/102691801-2292ef00-424a-11eb-8984-55cfdae02a9a.png)

![image](https://user-images.githubusercontent.com/9800933/102691823-5a019b80-424a-11eb-8ae3-4d78d432cc0c.png)

![image](https://user-images.githubusercontent.com/9800933/102691802-29216680-424a-11eb-8dd4-2932c535f7d3.png)

**Comment by Xmingbai** [comment]
目前就不支持，GPU温度检测不支持5500、5600、5700系列

**Comment by CodingOX** [comment]
不应该啊，之前有个朋友配置的 EFI是可以读取到的，但是睡眠有一点问题，这里我共享出来，希望能更完善。https://wwa.lanzous.com/iTO0vkodini

**Comment by Xmingbai** [comment]
我没说不支持所有显卡，GPU温度检测不支持5500、5600、5700系列

**Comment by CodingOX** [comment]
可能我的意思没表达出来，我的意思是说：相同配置的主机，我分享的那个 EFI 是可以获取 5700 的显卡信息的，温度、转速等。

**Comment by davidohne** [comment]
> Es sollte nicht sein, das zuvor von einem Freund konfigurierte EFI kann gelesen werden, aber es gibt ein Problem mit dem Schlaf, ich teile es hier, in der Hoffnung, es perfekter zu machen. [ https://wwa.lanzous.com/iTO0vkodini ](https://wwa.lanzous.com/iTO0vkodini)

This link is not working and looks like scam?!
